### ISSUE TITLE
About resolution

### ISSUE THREAD

**Issue by duzhenjiang113** [czq142857/implicit-decoder#15]
Hi, Zhiqin,
        It is a good job and I have a naive question about resolution of 3D object. Have you tried to improve the resolution of the shapes? I know that the resolution you used in paper is up to 256. The implicit field is a very good method, so can the resolution of the shape be improved without consuming a lot of memory?

**Comment by czq142857** [comment]
The output resolution in Fig 1 of our paper is actually 512^3. The resolution can be improved without consuming a lot of memory, but 256/512/1024 should be enough for most applications. Because a resolution of 1024 already produces so many vertices and triangles. Increasing the resolution beyond 256 usually does not produce more details.
