### ISSUE TITLE
Naive questions

### ISSUE THREAD

**Issue by wsh312** [czq142857/implicit-decoder#2]
Dear Zhiqin,

Thanks a lot for sharing your great work!

We have run the script you provide successfully, but we have some naive questions as I'm not familiar with the problem ;)

1) how should we read the output in the sample folder? Are they just rendering of the marching cube?
2) what's the input/output in both training and testing stage exactly?
3) how should we build our own dataset as h5 file?

It would be great if you have time to answer these questions, thanks!

Best,
Shihao

**Comment by czq142857** [comment]
Thanks for paying attention to our work.

1. The images are the 3-views (top, left, front), and the dae files are the outputs of the network rendered by marching cubes. During training, we only output images since it renders faster and gives us a better feel of the learned field. The dae files are generated when testing, and you can specify the sampling resolution.
2. It depends on the task. In IM-AE, the input is 64^3 voxel model; in IM-GAN, the input is 128-d feature code; in IM-SVR, the input is 128^2 image. The output is, in fact, an implicit field. We visualize the field by marching cubes.
3. I have updated the point-sampling code.

Best,
Zhiqin

**Comment by wsh312** [comment]
Thank you!!
