### ISSUE TITLE
Why do we need hierarchical flood fill for .binvox file before sampling points?

### ISSUE THREAD

**Issue by gaowei724** [czq142857/implicit-decoder#5]
Hi,
 I'm a CV novice. Thanks for your code, it's really helpful to me. I'm trying to rewrite the code for my own research.I try to rewrite the file "vox2pointvaluepair_from_binvox.py" for sampling points from binvox of 32^3. But I can not understand the function "hierarchicalfloodFill" in the code: Why do we need to do this before sampling points. And  another question: In the original function "hierarchicalfloodFill" (sampling points for binvox of 64^3), why do we need to compress voxel of 64^3 to 32^3 first and then restore it to 64^3.

Cheers.

**Comment by czq142857** [comment]
Hi.

_Why do we need hierarchical flood fill before sampling points?_
If you get the voxels via binvox, it is likely that only voxels on the surface of the shape are marked as "occupied". Since our method approximates an implicit field, we need all voxels inside the shape marked as "occupied", therefore we apply floodFill to the voxels before sampling points. 

_why do we need to compress voxel of 64^3 to 32^3 first and then restore it to 64^3?_
Because some shapes in Shapenet are not watertight. If we apply floodfill directly on high-resolution voxels, say 256^3, the interior of the shape will not be filled. So we do floodfill in a hierarchical (coarse to fine) manner.

Best,
Zhiqin

**Comment by gaowei724** [comment]
Thanks!
